[package]
name = "nod-krai-gi-luashell"
edition = "2021"
version.workspace = true

[dependencies]
bevy_app.workspace = true
bevy_ecs.workspace = true

nod-krai-gi-proto.workspace = true
nod-krai-gi-message.workspace = true
