[package]
name = "nod-krai-gi-social"
edition = "2024"
version.workspace = true

[dependencies]
bevy_app.workspace = true
bevy_ecs.workspace = true
common.workspace = true

nod-krai-gi-proto.workspace = true
nod-krai-gi-message.workspace = true
nod-krai-gi-event.workspace = true